import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div className="bg-[#1E1E1E] z-[-1] scrollbar-hide">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>      
         <Header/>
         <Main />
         <Projects />
         <Skills />
         <About />
         <Contact />
      </main>
    </div>
  )
}
